# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(package_name, file_path)
  package_path = `node --print "require.resolve('#{package_name}/package.json', { paths: ['#{__dir__}'] })"`.strip
  require File.join(File.dirname(package_path), file_path)
end

node_require('react-native', 'scripts/react_native_pods')

# Load Expo autolinking helpers (provides use_expo_modules!)
require File.join(File.dirname(`node --print "require.resolve('expo/package.json', { paths: ['#{__dir__}'] })"`), "scripts/autolinking")

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mobile' do
  config = use_native_modules!
  use_expo_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'fmt'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        else
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
        end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_USE_CONSTEVAL=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FMT_COMPILE_TIME_CHECKS=0'
      end
    end
  end
end
